artifacts_root: artifacts

dataset:
  root_dir: artifacts/dataset
  source_URL: s3://crosssellinsight/Cross Sell Insight dataset.zip
  s3_bucket: crosssellinsight
  s3_dataset: csi_dataset.zip
  local_data_file: artifacts/dataset/dataset.zip
  unzip_dir: artifacts/dataset

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/dataset/Cross Sell Insight dataset/data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/dataset/Cross Sell Insight dataset/data.csv

model_trainer:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: xg_boost.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
