artifacts_root: artifacts

dataset:
  root_dir: artifacts/dataset
  source_URL: s3://crosssellinsight/Cross Sell Insight dataset.zip
  s3_bucket: crosssellinsight
  s3_dataset: csi_dataset.zip
  local_data_file: artifacts/dataset/dataset.zip
  unzip_dir: artifacts/dataset

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/dataset/Cross Sell Insight dataset/data.csv
